# scene_id refers to the button number
# Possible scene_data values:
#   0: single press
#   1: holding button (event will repeat multiple times)
#   2: hold release (event fires when button is released if holding)
#   3: quick double press

- alias: Remotec button 1 single press
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remotec_1
      scene_id: 1
      scene_data: 0
  action:
    service: light.turn_on
    data:
      entity_id: light.some_light

- alias: Remotec button 2 double press
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.remotec_1
      scene_id: 2
      scene_data: 3  # double press
  action:
    service: light.turn_on
    data:
      entity_id: light.some_light
